<a href="https://colab.research.google.com/github/MarkellFultz/colab/blob/main/multiregre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
url='https://raw.githubusercontent.com/GrandmaCan/ML/main/Resgression/Salary_Data2.csv'
data=pd.read_csv(url)
data['EducationLevel']=data['EducationLevel'].map({"高中以下":0,"大學":1,"碩士以上":2})
data


YearsExperience  EducationLevel City  Salary
0               3.0               1  城市A    45.9
1               7.8               2  城市C    80.5
2               2.3               0  城市A    25.2
3               5.1               0  城市A    30.4
4              10.0               2  城市B    65.7
5               1.2               2  城市C    60.8
6               8.6               1  城市C    50.1
7               6.9               2  城市A    70.3
8               4.2               1  城市A    40.7
9               2.4               0  城市A    28.1
10              5.3               0  城市A    32.0
11              3.9               1  城市A    48.3
12              7.2               2  城市C    84.2
13             10.0               2  城市B    70.9
14              1.5               2  城市C    62.4
15              8.4               1  城市C    55.6
16              6.5               2  城市A    72.7
17              4.8               1  城市A    42.9
18              2.1               0  城市A    26.5
19              5.2               0  城市A    31.6
20              3.5               1  城市A    43.8
21              7.6               2  城市C    78.3
22             10.0               2  城市B    63.6
23              1.8               2  城市C    58.0
24              8.2               1  城市C    48.3
25              6.3               2  城市A    68.4
26              4.6               1  城市A    38.5
27              2.5               0  城市A    24.9
28              5.0               0  城市A    29.7
29              3.6               1  城市A    41.6
30              7.4               2  城市C    76.9
31             10.0               2  城市B    60.2
32              1.7               2  城市C    56.3
33              8.0               1  城市C    45.2
34              6.1               2  城市A    65.9
35              4.3               1  城市A    36.7

In [ ]:
#one hot encoding轉換單一欄位
from sklearn.preprocessing import OneHotEncoder
OHE=OneHotEncoder()
OHE.fit(data[['City']])
city_encoded=OHE.transform(data[['City']]).toarray()
print(city_encoded)
data[["CityA","CityB","CityC",]]=city_encoded


[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [ ]:
data=data.drop(["City","CityC"],axis=1)
data

YearsExperience  EducationLevel  Salary  CityA  CityB
0               3.0               1    45.9    1.0    0.0
1               7.8               2    80.5    0.0    0.0
2               2.3               0    25.2    1.0    0.0
3               5.1               0    30.4    1.0    0.0
4              10.0               2    65.7    0.0    1.0
5               1.2               2    60.8    0.0    0.0
6               8.6               1    50.1    0.0    0.0
7               6.9               2    70.3    1.0    0.0
8               4.2               1    40.7    1.0    0.0
9               2.4               0    28.1    1.0    0.0
10              5.3               0    32.0    1.0    0.0
11              3.9               1    48.3    1.0    0.0
12              7.2               2    84.2    0.0    0.0
13             10.0               2    70.9    0.0    1.0
14              1.5               2    62.4    0.0    0.0
15              8.4               1    55.6    0.0    0.0
16              6.5               2    72.7    1.0    0.0
17              4.8               1    42.9    1.0    0.0
18              2.1               0    26.5    1.0    0.0
19              5.2               0    31.6    1.0    0.0
20              3.5               1    43.8    1.0    0.0
21              7.6               2    78.3    0.0    0.0
22             10.0               2    63.6    0.0    1.0
23              1.8               2    58.0    0.0    0.0
24              8.2               1    48.3    0.0    0.0
25              6.3               2    68.4    1.0    0.0
26              4.6               1    38.5    1.0    0.0
27              2.5               0    24.9    1.0    0.0
28              5.0               0    29.7    1.0    0.0
29              3.6               1    41.6    1.0    0.0
30              7.4               2    76.9    0.0    0.0
31             10.0               2    60.2    0.0    1.0
32              1.7               2    56.3    0.0    0.0
33              8.0               1    45.2    0.0    0.0
34              6.1               2    65.9    1.0    0.0
35              4.3               1    36.7    1.0    0.0

In [ ]:
from sklearn.model_selection import train_test_split


x=data[["YearsExperience","EducationLevel","CityA","CityB"]]
y=data["Salary"]
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=87)#分割兩成資料做測試集 變數random_state可固定 test_size決定分割大小
X_train=X_train.to_numpy()
X_test=X_test.to_numpy()
Y_train=Y_train.to_numpy()
Y_test=Y_test.to_numpy()


In [ ]:
def compute_cost(x,y,b1,b2):
  pre_y=(x*b1).sum(axis=1)+b2
  cost=((y-pre_y)**2).mean()
  return cost

In [ ]:
#平方法
import numpy as np
b1=np.array([0,2,2,4])
b2=0
compute_cost(X_train,Y_train,b1,b2)

np.float64(2437.7371428571428)

In [ ]:
#Gradient
#斜率計算(真實y-pred_y)平方=(y-(w1x1+w2x2...wnxn+b2))平方偏微
#         EX:對w1 得到 2*(-x1)*(y-(w1x1+w2x2...wnxn+b2))=2*(x1)*(pred_y-真實y)
#                ↑ ↑
# 實作上把2交給learning rate去變化 (0-(w1+0+0+0+0))

#除b2外因為b2沒有函數項目因此(pred_y-真實y)
pre_y=(X_train*b1).sum(axis=1)+b2
b2_grediant=(pre_y-Y_train).mean()
'''
x1=X_train[:,0]
w1_gredient=(X_train[:,0]*(pre_y-Y_train)).mean()
w2_gredient=(X_train[:,1]*(pre_y-Y_train)).mean()
w3_gredient=(X_train[:,2]*(pre_y-Y_train)).mean()
w4_gredient=(X_train[:,3]*(pre_y-Y_train)).mean()
w1_gredient,w2_gredient,w3_gredient,w4_gredient'''
#計算透過迴圈得到每一個變數斜率
def compute_gradient(x,y,b,b2):


  pre_y=(x*b).sum(axis=1)+b2
  feature=x.shape[1]
  w_gradient=np.zeros(feature)
  b2_gradiant=(pre_y-y).mean()
  for i in range(feature):
    w_gradient[i]=(x[:,i]*(pre_y-y)).mean()
  return w_gradient,b2_gradiant


In [ ]:
b=[0,0,0,0]
b2=1
w_gradient ,b2_gradiant=compute_gradient(X_train,Y_train,b,b2)
w_gradient ,b2_gradiant

(array([-315.87142857,  -70.35      ,  -21.15      ,   -9.15714286]),
 np.float64(-49.949999999999996))

In [ ]:
learning_rate=0.001
b=[1,2,2,4]
b2=1

print(compute_cost(X_train,Y_train,b,b2))
#學習一次
w_gradient ,b2_grediant=compute_gradient(X_train,Y_train,b,b2)
b=b-learning_rate*w_gradient
b2=b2-learning_rate*b2_grediant
b,b2
print(compute_cost(X_train,Y_train,b,b2 ))


1806.2914285714287
1675.283646825475


In [ ]:

def gradient_descent(x,y,b1,b2,learning_rate,cost,coumpute_gradient,run_itter,p_itter):

  b1=b1
  b2=b2
  cost_history=[]
  b1_history=[]
  b2_history=[]
  p_itter=p_itter
  for i in range(run_itter):
    b1_gradient,b2_gradient=compute_gradient(x,y,b1,b2)
    b1=b1-b1_gradient*learning_rate
    b2=b2-b2_gradient*learning_rate
    costx=cost(x,y,b1,b2)
    b1_history.append(b1)
    b2_history.append(b2)
    cost_history.append(costx)

    if(i%p_itter==0):
      print(f'第{i:5}次:{costx}, b1:{b1}, b2:{b2},b1_gradient:{b1_gradient}, b2_gradient:{b2_gradient}')
  return b1,b2,cost_history,b1_history,b2_history

In [ ]:

learning_rate=1.0e-3
b = np.array([1, 2, 2, 4])  # ✅ 正確寫法：b 為 numpy array
b2 = 1

# 呼叫
b1_final, b2_final, cost_history, b1_history, b2_history = gradient_descent(
    X_train, Y_train, b, b2, learning_rate, compute_cost, compute_gradient, 20000, 1000)



第    0次:1675.283646825475, b1:[1.24862429 2.05672857 2.01693929 4.00658571], b2:1.0400714285714285,b1_gradient:[-248.62428571  -56.72857143  -16.93928571   -6.58571429], b2_gradient:-40.07142857142858
第 1000次:135.74644411542602, b1:[ 4.86878498 10.14566549  4.12709829  2.36750126], b2:5.145782504431858,b1_gradient:[ 1.43688108 -5.43720143 -1.27414026  1.62784422], b2_gradient:-2.6772543834882825
第 2000次:79.8510766504797, b1:[ 3.73611432 14.42180894  5.03071686  0.89436792], b2:7.355666045507624,b1_gradient:[ 0.87495496 -3.29235446 -0.59175135  1.33664064], b2_gradient:-1.812068262599772
第 3000次:57.25573447931964, b1:[ 3.04702639 17.00430383  5.40122389 -0.33414578], b2:8.877469058511744,b1_gradient:[ 0.53167384 -1.98112082 -0.18506676  1.13191529], b2_gradient:-1.2742254123414114
第 4000次:47.36040832000051, b1:[ 2.62880047 18.55168932  5.45614476 -1.38747045], b2:9.970132111195866,b1_gradient:[ 0.32218636 -1.18003651  0.05341713  0.98213594], b2_gradient:-0.937326103950869
第 5000次:42.41

In [ ]:
y_final=(b1_final*X_test).sum(axis=1)+b2_final
pd.DataFrame({"預測值":y_final,"真實值":Y_test})

預測值   真實值
0  44.419998  43.8
1  70.442164  72.7
2  58.556360  60.8
3  22.351404  24.9
4  59.544754  56.3
5  21.956046  25.2
6  71.603149  80.5
7  71.232878  70.3

In [ ]:
compute_cost(X_test,Y_test,b1_final,b2_final)

np.float64(14.760919804552906)

In [ ]:
#特徵縮放標準差

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)
X_train

array([[-0.49250409, -0.2354408 ,  0.93094934, -0.40824829],
       [-0.60806371, -0.2354408 ,  0.93094934, -0.40824829],
       [ 0.085294  ,  1.0830277 ,  0.93094934, -0.40824829],
       [-0.87770282, -0.2354408 ,  0.93094934, -0.40824829],
       [ 0.16233375,  1.0830277 ,  0.93094934, -0.40824829],
       [-0.41546434, -0.2354408 ,  0.93094934, -0.40824829],
       [ 0.50901261,  1.0830277 , -1.07417231, -0.40824829],
       [ 1.58756905,  1.0830277 , -1.07417231,  2.44948974],
       [-1.57106053,  1.0830277 , -1.07417231, -0.40824829],
       [-1.45550091, -1.55390931,  0.93094934, -0.40824829],
       [-0.7621432 , -0.2354408 ,  0.93094934, -0.40824829],
       [ 0.6630921 ,  1.0830277 , -1.07417231, -0.40824829],
       [ 1.58756905,  1.0830277 , -1.07417231,  2.44948974],
       [ 0.89421134, -0.2354408 , -1.07417231, -0.40824829],
       [-0.29990473, -1.55390931,  0.93094934, -0.40824829],
       [ 1.58756905,  1.0830277 , -1.07417231,  2.44948974],
       [-0.64658358, -0.

In [ ]:

learning_rate=1.0e-3
b = np.array([1, 2, 2, 4])  # ✅ 正確寫法：b 為 numpy array
b2 = 1

# 呼叫
b1_final, b2_final, cost_history, b1_history, b2_history = gradient_descent(
    X_train, Y_train, b, b2, learning_rate, compute_cost, compute_gradient, 20000, 1000)



第    0次:2704.098469896066, b1:[1.00535305 2.01220449 1.99038323 4.00112136], b2:1.04995,b1_gradient:[ -5.35305402 -12.20449464   9.61677346  -1.12136056], b2_gradient:-49.95
第 1000次:395.56304799570813, b1:[ 2.38452431  8.44603734 -2.0990062   2.16718369], b2:32.60197991915765,b1_gradient:[ 0.09884817 -3.39937794  1.40830705  2.59131025], b2_gradient:-18.36638646730966
第 2000次:82.2357526265828, b1:[ 2.27514856e+00  1.07920026e+01 -2.78798122e+00  4.25413791e-03], b2:44.203516962668445,b1_gradient:[ 0.00784784 -1.6196533   0.25392269  1.69722236], b2_gradient:-6.75323627360516
第 3000次:36.201743175628316, b1:[ 2.37811469 12.00877134 -2.85476104 -1.31797348], b2:48.46934905387828,b1_gradient:[-0.18865601 -0.90114324 -0.06391034  1.00864267], b2_gradient:-2.4831340802019213
第 4000次:28.45461516735728, b1:[ 2.60811932 12.70784484 -2.7272214  -2.11175809], b2:50.03787599665729,b1_gradient:[-0.25479662 -0.53557657 -0.17056397  0.61686444], b2_gradient:-0.9130370403830945
第 5000次:26.664092757949